version: "3.9"

services:
  backend:
    build: ./backend
    container_name: automation-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["npm", "start"]

  frontend:
    build: ./frontend
    container_name: automation-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]
